#cloud-config
package_update: true

packages:
  - docker.io
  - git

runcmd:
  - systemctl start docker
  - systemctl enable docker
  - mkdir -p /usr/local/lib/docker/cli-plugins
  - curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/lib/docker/cli-plugins/docker-compose
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  - git clone https://github.com/karinakystsiv/open-data-ai-analytics.git /app
  - cd /app && docker compose up -d --build
  - sleep 30
  - cd /app && docker compose -f monitoring/docker-compose.monitoring.yml up -d
