apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: analytics
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web
          image: web-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "1.0"
          volumeMounts:
            - name: reports
              mountPath: /app/reports
      volumes:
        - name: reports
          hostPath:
            path: /app/reports
            type: DirectoryOrCreate
